In [1]:
import numpy as np

from minesweeper import Minesweeper

In [2]:
game = Minesweeper(num_mine=10, sizeX=8, sizeY=8)
print(game.num_mine_around)
print('-------------------')
print(game.get_state())

[[1. 1. 0. 1. 2. 2. 3. 1.]
 [1. 2. 1. 1. 3. 2. 4. 1.]
 [2. 2. 3. 2. 2. 1. 3. 1.]
 [1. 2. 2. 1. 1. 0. 1. 1.]
 [0. 1. 2. 3. 2. 1. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
-------------------
[[-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]]


In [6]:
game.mines

array([[0., 0., 0., 0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
game.action(0)

In [5]:
print(game.get_state())

[[ 1. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]]


In [7]:
game.action(2)

In [8]:
print(game.get_state())

[[ 1.  1.  0.  1. -5. -5. -5. -5.]
 [-5.  2.  1.  1. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]]
