In [1]:
import numpy as np

from minesweeper import Minesweeper

In [4]:
game = Minesweeper(num_mine=10, sizeX=8, sizeY=8)
print(game.num_mine_around)
print('-------------------')
print(game.get_state())

[[0. 0. 0. 1. 2. 2. 1. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 2. 2. 2. 1. 0.]
 [0. 1. 0. 1. 0. 0. 1. 1.]
 [1. 3. 3. 3. 1. 1. 1. 0.]
 [1. 1. 1. 2. 0. 1. 2. 2.]
 [1. 2. 2. 3. 3. 3. 2. 0.]
 [0. 0. 0. 1. 1. 1. 2. 1.]]
-------------------
[[-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]
 [-5. -5. -5. -5. -5. -5. -5. -5.]]


In [5]:
game.action(28)

win 0 dead 0


(0, 0)

In [6]:
game.get_state()

array([[-5., -5., -5., -5., -5., -5., -5., -5.],
       [-5., -5., -5., -5., -5., -5., -5., -5.],
       [-5., -5., -5.,  2.,  2.,  2.,  1., -5.],
       [-5., -5., -5.,  1.,  0.,  0.,  1., -5.],
       [-5., -5., -5.,  3.,  1.,  1.,  1., -5.],
       [-5., -5., -5., -5., -5., -5., -5., -5.],
       [-5., -5., -5., -5., -5., -5., -5., -5.],
       [-5., -5., -5., -5., -5., -5., -5., -5.]])